## Importing neccesary libraries

In [1]:
import pandas as pd
import numpy as np

## Importing the dataset

In [2]:
raw_dataset = pd.read_csv('adult.data')
raw_dataset

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country target  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[32561 rows x 15 columns]

In [3]:
#dataset = raw_dataset
#for column in raw_dataset.columns:
#    dataset = dataset[dataset[column] != '?']

## Replacing missing values in a column with the most frequent value in the column 

In [4]:
dataset = raw_dataset
for column in raw_dataset.columns:
    dataset[column] = dataset[column].replace(['?'], [dataset[column].value_counts().index[0]])

In [5]:
dataset

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country target  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[32561 rows x 15 columns]

## Converting all Continuos columns to Categorical columns for Naive Bayes Classifier

In [6]:
dataset['age'] = pd.cut(dataset['age'], [17, 20, 30, 40, 50, 60, 70, 80, 90], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8], include_lowest=True)

In [7]:
dataset['age'].value_counts()

3    8546
2    8162
4    6983
5    4128
1    2410
6    1792
7     441
8      99
Name: age, dtype: int64

In [8]:
dataset['hours-per-week'] = pd.cut(dataset['hours-per-week'], [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], include_lowest=True)

In [9]:
dataset['hours-per-week'].value_counts()

4     17735
5      5938
6      2533
3      2317
2      2192
1       736
7       612
8       290
10      110
9        98
Name: hours-per-week, dtype: int64

In [10]:
dataset['fnlwgt'] = pd.cut(dataset['fnlwgt'], [0, 150000, 300000, 450000, 600000, 750000, 900000, 1050000, 1200000, 1350000, 1500000], right=True, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], include_lowest=True)

In [11]:
dataset['fnlwgt'].value_counts()

2     16177
1     11972
3      3769
4       501
5       104
6        18
7        10
8         5
10        3
9         2
Name: fnlwgt, dtype: int64

In [12]:
dataset['capital-gain'] = pd.cut(dataset['capital-gain'], [0, 1, 20000, 40000, 80000, 100000], right=True, labels=[1, 2, 3, 4, 5], include_lowest=True)

In [13]:
dataset['capital-gain'].value_counts()

1    29849
2     2459
5      159
3       92
4        2
Name: capital-gain, dtype: int64

In [14]:
dataset['capital-loss'] = pd.cut(dataset['capital-loss'], [0, 1, 1000, 2000, 3000, 4000, 5000], right=True, labels=[1, 2, 3, 4, 5, 6], include_lowest=True)

In [15]:
dataset['capital-loss'].value_counts()

1    31042
3     1158
4      314
2       36
5        8
6        3
Name: capital-loss, dtype: int64

In [16]:
dataset['target'].replace(['>50K', '<=50K'], [1, 0], inplace=True)
dataset

age         workclass fnlwgt   education  education-num  \
0       3         State-gov      1   Bachelors             13   
1       4  Self-emp-not-inc      1   Bachelors             13   
2       3           Private      2     HS-grad              9   
3       5           Private      2        11th              7   
4       2           Private      3   Bachelors             13   
...    ..               ...    ...         ...            ...   
32556   2           Private      2  Assoc-acdm             12   
32557   3           Private      2     HS-grad              9   
32558   5           Private      2     HS-grad              9   
32559   2           Private      2     HS-grad              9   
32560   5      Self-emp-inc      2     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

      capital-gain capital-loss hours-per-week native-country  target  
0                2            1              4  United-States       0  
1                1            1              2  United-States       0  
2                1            1              4  United-States       0  
3                1            1              4  United-States       0  
4                1            1              4           Cuba       0  
...            ...          ...            ...            ...     ...  
32556            1            1              4  United-States       0  
32557            1            1              4  United-States       1  
32558            1            1              4  United-States       0  
32559            1            1              2  United-States       0  
32560            2            1              4  United-States       1  

[32561 rows x 15 columns]

## Spilting the given data into training and testing data

In [17]:
training_data = dataset.sample(frac=2/3)
training_data

age         workclass fnlwgt     education  education-num  \
4051    2  Self-emp-not-inc      2     Bachelors             13   
12299   5           Private      1       HS-grad              9   
16723   2         State-gov      2  Some-college             10   
16686   2           Private      2       HS-grad              9   
5726    1           Private      2       HS-grad              9   
...    ..               ...    ...           ...            ...   
20430   1           Private      1           9th              5   
10969   2           Private      2       HS-grad              9   
5251    3         Local-gov      2       Masters             14   
3575    4           Private      3  Some-college             10   
29605   6           Private      2    Assoc-acdm             12   

           marital-status         occupation   relationship   race     sex  \
4051        Never-married     Prof-specialty  Not-in-family  Black    Male   
12299  Married-civ-spouse     Prof-specialty        Husband  White    Male   
16723       Never-married       Adm-clerical      Own-child  White  Female   
16686       Never-married  Handlers-cleaners  Not-in-family  White    Male   
5726            Separated  Machine-op-inspct      Own-child  White    Male   
...                   ...                ...            ...    ...     ...   
20430       Never-married      Other-service      Own-child  White  Female   
10969  Married-civ-spouse    Farming-fishing        Husband  White    Male   
5251   Married-civ-spouse     Prof-specialty           Wife  White  Female   
3575   Married-civ-spouse    Exec-managerial        Husband  White    Male   
29605  Married-civ-spouse    Exec-managerial        Husband  White    Male   

      capital-gain capital-loss hours-per-week native-country  target  
4051             1            1              4  United-States       0  
12299            1            3              7  United-States       1  
16723            1            1              3  United-States       0  
16686            1            1              4  United-States       0  
5726             1            1              4  United-States       0  
...            ...          ...            ...            ...     ...  
20430            1            1              4  United-States       0  
10969            1            1              6  United-States       0  
5251             1            1              4  United-States       1  
3575             1            3              4  United-States       1  
29605            1            1              5  United-States       0  

[21707 rows x 15 columns]

In [18]:
testing_data = dataset.drop(training_data.index)
testing_data

age         workclass fnlwgt     education  education-num  \
2       3           Private      2       HS-grad              9   
7       5  Self-emp-not-inc      2       HS-grad              9   
8       3           Private      1       Masters             14   
14      3           Private      1     Assoc-voc             11   
17      3           Private      2       HS-grad              9   
...    ..               ...    ...           ...            ...   
32541   4           Private      2       HS-grad              9   
32543   4         Local-gov      1    Assoc-acdm             12   
32544   3           Private      2       Masters             14   
32550   4  Self-emp-not-inc      1  Some-college             10   
32553   3           Private      1       Masters             14   

           marital-status         occupation   relationship  \
2                Divorced  Handlers-cleaners  Not-in-family   
7      Married-civ-spouse    Exec-managerial        Husband   
8           Never-married     Prof-specialty  Not-in-family   
14     Married-civ-spouse       Craft-repair        Husband   
17          Never-married  Machine-op-inspct      Unmarried   
...                   ...                ...            ...   
32541           Separated     Prof-specialty  Not-in-family   
32543            Divorced     Prof-specialty      Unmarried   
32544            Divorced      Other-service  Not-in-family   
32550  Married-civ-spouse       Craft-repair        Husband   
32553       Never-married       Tech-support  Not-in-family   

                     race     sex capital-gain capital-loss hours-per-week  \
2                   White    Male            1            1              4   
7                   White    Male            1            1              5   
8                   White  Female            2            1              5   
14     Asian-Pac-Islander    Male            1            1              4   
17                  White    Male            1            1              4   
...                   ...     ...          ...          ...            ...   
32541               Black  Female            1            1              4   
32543               White  Female            1            1              5   
32544               Other  Female            1            1              3   
32550               White    Male            1            1              5   
32553  Asian-Pac-Islander    Male            1            1              2   

      native-country  target  
2      United-States       0  
7      United-States       1  
8      United-States       1  
14     United-States       1  
17     United-States       0  
...              ...     ...  
32541  United-States       0  
32543  United-States       0  
32544  United-States       0  
32550  United-States       0  
32553         Taiwan       0  

[10854 rows x 15 columns]

## Function which precomputes all conditional probabilities for each feature in the dataset

In [19]:
def precomp(training_data, alpha):
    prec = []
    positive_data = training_data[training_data['target'] == 1]
    negetive_data = training_data[training_data['target'] == 0]
    
    for column in training_data.columns[:-1]:
        prob = {}
        for value in training_data[column].value_counts().keys():
            prob[value] = []
            prob[value].append((len(negetive_data[negetive_data[column] == value]) + alpha)/(len(negetive_data)+14*alpha))
            prob[value].append((len(positive_data[positive_data[column] == value]) + alpha)/(len(positive_data)+14*alpha))
            prob[-1] = [alpha/(len(negetive_data) + 14*alpha), alpha/(len(positive_data) + 14*alpha)]
        prec.append(prob);
        
    return prec

## Function which returns the prior probability for a given class

In [20]:
def prior(training_data, target):
    return len(training_data[training_data['target'] == target])/len(training_data)

## Function which returns the conditonal probability for a certain feature value given precomputed values, feature, value of feature and the target class

In [21]:
def conditional_prob(prec, feature, value, target):
    if value in prec[feature]:
        prob = prec[feature][value][target]
        
    else:
        prob = 0
        
    if (prob==0):
        prob = prec[feature][-1][target]
    
    return prob

## Function which returns the predicted class for a testing example 

In [22]:
def pred(testing_example, prec, pr1, pr2):
    p1 = pr1
    for i in range(14):
        p1 *= conditional_prob(prec, i, testing_example[i], 1)
    
    p2 = pr2
    for i in range(14):
        p2 *= conditional_prob(prec, i, testing_example[i], 0)
    
    if (p1 > p2):
        return 1
    else:
        return 0

## Function which evaluates the model and returns the confusion matrix

In [23]:
def evaluate(testing_set, prec, pr1, pr2):
    c_mat = np.zeros((2, 2))
    for testing_example in testing_set:
        y = testing_example[14]
        h = pred(testing_example, prec, pr1, pr2)
        if y==1 and h==1:
            c_mat[1][1]+=1
            
        elif y==1 and h==0:
            c_mat[1][0]+=1
            
        elif y==0 and h==0: 
            c_mat[0][0]+=1
            
        else:
            c_mat[0][1]+=1
            
    return c_mat

## Functions for Evaluation Metrics

In [24]:
def accuracy(c_mat):
    return (c_mat[0][0]+c_mat[1][1])/(c_mat[0][0] + c_mat[0][1] + c_mat[1][0] + c_mat[1][1])*100

def precision(c_mat):
    return (c_mat[1][1])/(c_mat[1][1] + c_mat[0][1])*100

def recall(c_mat):
    return (c_mat[1][1])/(c_mat[1][0] + c_mat[1][1])*100

def f1_score(c_mat):
    prec = precision(c_mat)
    rec = recall(c_mat)
    
    return (2*rec*prec)/(prec + rec)

In [25]:
prec = precomp(training_data, 120)
prec

[{3: [0.23179391203831123, 0.25043478260869567],
  -1: [0.006605383387460781, 0.017391304347826087],
  2: [0.2817196014752023, 0.08318840579710145],
  4: [0.16590521274838993, 0.27594202898550724],
  5: [0.09886057136566302, 0.16318840579710145],
  1: [0.09599823856443002, 0.017681159420289853],
  6: [0.0564209831012275, 0.06101449275362319],
  7: [0.019926239885506687, 0.025072463768115942],
  8: [0.009742940496504652, 0.019130434782608695]},
 {'Private': [0.7155832003082512, 0.5146376811594203],
  -1: [0.006605383387460781, 0.017391304347826087],
  'Self-emp-not-inc': [0.0728243518467551, 0.08898550724637681],
  'Local-gov': [0.06280618704243959, 0.07681159420289856],
  'State-gov': [0.04183409478725161, 0.05217391304347826],
  'Self-emp-inc': [0.02548577090328618, 0.07710144927536232],
  'Federal-gov': [0.02774261022733528, 0.051159420289855075],
  'Without-pay': [0.0071558320030825125, 0.017391304347826087],
  'Never-worked': [0.00693565255683382, 0.017391304347826087]},
 {2: [0.45

In [26]:
pr1 = prior(training_data, 1)
pr2 = prior(training_data, 0)
pr1 + pr2

1.0

In [27]:
testing_set = testing_data.to_numpy()
c_mat = evaluate(testing_set, prec, pr1, pr2)
acc = accuracy(c_mat)
prec = precision(c_mat)
rec = recall(c_mat)
print(c_mat)
print(f"Accuracy: {acc}")
print(f"Preision: {prec}")
print(f"Recall: {rec}")

[[7558.  675.]
 [1149. 1472.]]
Accuracy: 83.1951354339414
Preision: 68.56078248719143
Recall: 56.16177031667302


## Naive Bayes Classifier using Laplace Smoothing Technique

In [28]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    training_data = dataset.sample(frac=2/3)
    testing_data = dataset.drop(training_data.index)
    testing_set = testing_data.to_numpy()
    
    prec = precomp(training_data, 100)
    pr1 = prior(training_data, 1)
    pr2 = prior(training_data, 0)
    c_mat = evaluate(testing_set, prec, pr1, pr2)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    print(f"F1-Score = {f1_score(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    f1_list[i] = f1_score(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7503.  735.]
 [1062. 1554.]]
Accuracy = 83.44389165284689
Precision = 67.88990825688074
Recall = 59.403669724770644
F1-Score = 63.36391437308869


Model No.2
Confusion Matrix:
[[7497.  748.]
 [1101. 1508.]]
Accuracy = 82.96480560162152
Precision = 66.84397163120568
Recall = 57.799923342276735
F1-Score = 61.99383350462487


Model No.3
Confusion Matrix:
[[7480.  703.]
 [1140. 1531.]]
Accuracy = 83.0200847613783
Precision = 68.53178155774395
Recall = 57.319356046424566
F1-Score = 62.426095820591236


Model No.4
Confusion Matrix:
[[7543.  687.]
 [1126. 1498.]]
Accuracy = 83.29648056016215
Precision = 68.558352402746
Recall = 57.088414634146346
F1-Score = 62.29985443959243


Model No.5
Confusion Matrix:
[[7551.  764.]
 [1039. 1500.]]
Accuracy = 83.38861249309011
Precision = 66.25441696113074
Recall = 59.078377313903104
F1-Score = 62.46096189881324


Model No.6
Confusion Matrix:
[[7523.  799.]
 [1047. 1485.]]
Accuracy = 82.9924451814999
Precision = 65.017513134

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [30]:
target = dataset['target']
new_dataset = dataset.drop('target', axis=1)

In [31]:
new_dataset

age         workclass fnlwgt   education  education-num  \
0       3         State-gov      1   Bachelors             13   
1       4  Self-emp-not-inc      1   Bachelors             13   
2       3           Private      2     HS-grad              9   
3       5           Private      2        11th              7   
4       2           Private      3   Bachelors             13   
...    ..               ...    ...         ...            ...   
32556   2           Private      2  Assoc-acdm             12   
32557   3           Private      2     HS-grad              9   
32558   5           Private      2     HS-grad              9   
32559   2           Private      2     HS-grad              9   
32560   5      Self-emp-inc      2     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

      capital-gain capital-loss hours-per-week native-country  
0                2            1              4  United-States  
1                1            1              2  United-States  
2                1            1              4  United-States  
3                1            1              4  United-States  
4                1            1              4           Cuba  
...            ...          ...            ...            ...  
32556            1            1              4  United-States  
32557            1            1              4  United-States  
32558            1            1              4  United-States  
32559            1            1              2  United-States  
32560            2            1              4  United-States  

[32561 rows x 14 columns]

In [271]:
#new_dataset['workclass'].replace(new_dataset['workclass'].value_counts().keys(), list(range(len(new_dataset['workclass'].value_counts()))), inplace=True)
#new_dataset['marital-status'].replace(new_dataset['marital-status'].value_counts().keys(), list(range(len(new_dataset['marital-status'].value_counts()))), inplace=True)
#new_dataset['education'].replace(new_dataset['education'].value_counts().keys(), list(range(len(new_dataset['education'].value_counts()))), inplace=True)
#new_dataset['occupation'].replace(new_dataset['occupation'].value_counts().keys(), list(range(len(new_dataset['occupation'].value_counts()))), inplace=True)
#new_dataset['relationship'].replace(new_dataset['relationship'].value_counts().keys(), list(range(len(new_dataset['relationship'].value_counts()))), inplace=True)
#new_dataset['race'].replace(new_dataset['race'].value_counts().keys(), list(range(len(new_dataset['race'].value_counts()))), inplace=True)
#new_dataset['sex'].replace(new_dataset['sex'].value_counts().keys(), list(range(len(new_dataset['sex'].value_counts()))), inplace=True)
#new_dataset['native-country'].replace(new_dataset['native-country'].value_counts().keys(), list(range(len(new_dataset['native-country'].value_counts()))), inplace=True)

## Converting all Categorical Features to Numerical Features for Logistic Regression and K Nearest-Neighbors

In [32]:
for column in dataset.columns:
    if (dataset[column].dtype == 'object'):
        new_dataset[column].replace(new_dataset[column].value_counts().keys(), list(range(len(new_dataset[column].value_counts()))), inplace=True)

In [33]:
new_dataset

age  workclass fnlwgt  education  education-num  marital-status  \
0       3          3      1          2             13               1   
1       4          1      1          2             13               0   
2       3          0      2          0              9               2   
3       5          0      2          5              7               0   
4       2          0      3          2             13               0   
...    ..        ...    ...        ...            ...             ...   
32556   2          0      2          6             12               0   
32557   3          0      2          0              9               0   
32558   5          0      2          0              9               4   
32559   2          0      2          0              9               1   
32560   5          4      2          0              9               0   

       occupation  relationship  race  sex capital-gain capital-loss  \
0               3             1     0    0            2            1   
1               2             0     0    0            1            1   
2               8             1     0    0            1            1   
3               8             0     1    0            1            1   
4               0             4     1    1            1            1   
...           ...           ...   ...  ...          ...          ...   
32556          10             4     0    1            1            1   
32557           6             0     0    0            1            1   
32558           3             3     0    1            1            1   
32559           3             2     0    0            1            1   
32560           2             4     0    1            2            1   

      hours-per-week  native-country  
0                  4               0  
1                  2               0  
2                  4               0  
3                  4               0  
4                  4               8  
...              ...             ...  
32556              4               0  
32557              4               0  
32558              4               0  
32559              2               0  
32560              4               0  

[32561 rows x 14 columns]

## Logistic Regression using Scikit Learn

In [34]:
# Logistic Regression
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    logreg = LogisticRegression(max_iter = 10000)
    logreg.fit(x_train, y_train)
    y_pred = logreg.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7705  559]
 [1278 1312]]
Accuracy = 83.07536392113506
Precision = 70.12292891501872
Recall = 50.656370656370655
F1-Score = 58.82089217664201


Model No.2
Confusion Matrix:
[[7673  562]
 [1296 1323]]
Accuracy = 82.88188686198636
Precision = 70.18567639257294
Recall = 50.51546391752577
F1-Score = 58.74777975133214


Model No.3
Confusion Matrix:
[[7595  592]
 [1279 1388]]
Accuracy = 82.76211534918002
Precision = 70.1010101010101
Recall = 52.04349456317961
F1-Score = 59.73746503120293


Model No.4
Confusion Matrix:
[[7602  578]
 [1309 1365]]
Accuracy = 82.6147042564953
Precision = 70.25218733916624
Recall = 51.047120418848166
F1-Score = 59.12930474333983


Model No.5
Confusion Matrix:
[[7710  551]
 [1257 1336]]
Accuracy = 83.34254652662612
Precision = 70.80021197668258
Recall = 51.52333204782106
F1-Score = 59.64285714285714


Model No.6
Confusion Matrix:
[[7705  543]
 [1322 1284]]
Accuracy = 82.81739450893679
Precision = 70.27914614121511
Recall = 49.27091327

## K Nearest Neighbors (1 Neighbor) using Scikit Learn

In [284]:
# K Nearest Neighbours (No. of Neighbors = 1)
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    knn = KNeighborsClassifier(n_neighbors=1)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7104 1130]
 [1169 1451]]
Accuracy = 78.81886861986365
Precision = 56.218519953506394
Recall = 55.38167938931298
F1-Score = 55.796962122668724


Model No.2
Confusion Matrix:
[[7148 1102]
 [1176 1428]]
Accuracy = 79.01234567901234
Precision = 56.44268774703557
Recall = 54.83870967741935
F1-Score = 55.62913907284768


Model No.3
Confusion Matrix:
[[7091 1115]
 [1201 1447]]
Accuracy = 78.66224433388612
Precision = 56.47931303669008
Recall = 54.64501510574018
F1-Score = 55.547024952015356


Model No.4
Confusion Matrix:
[[7178 1083]
 [1205 1388]]
Accuracy = 78.92021374608439
Precision = 56.17159044921085
Recall = 53.52873119938295
F1-Score = 54.81832543443919


Model No.5
Confusion Matrix:
[[7076 1111]
 [1185 1482]]
Accuracy = 78.84650819974203
Precision = 57.15387581951408
Recall = 55.56805399325084
F1-Score = 56.349809885931556


Model No.6
Confusion Matrix:
[[7149 1035]
 [1219 1451]]
Accuracy = 79.23346231803943
Precision = 58.3668543845535
Recall = 54.34456

## K Nearest Neighbors (3 Neighbors) using Scikit Learn

In [287]:
# K Nearest Neighbours (No. of Neighbors = 3)
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
f1_list = np.zeros(10)
for i in range(10):
    
    x_train, x_test, y_train, y_test = train_test_split(new_dataset, target, test_size=1/3)
    
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(x_train, y_train)
    y_pred = knn.predict(x_test)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{metrics.confusion_matrix(y_test, y_pred)}")
    print(f"Accuracy = {metrics.accuracy_score(y_test, y_pred)*100}")
    print(f"Precision = {metrics.precision_score(y_test, y_pred)*100}")
    print(f"Recall = {metrics.recall_score(y_test, y_pred)*100}")
    print(f"F1-Score = {metrics.f1_score(y_test, y_pred)*100}")
    
    accuracy_list[i] =  metrics.accuracy_score(y_test, y_pred)*100
    precision_list[i] = metrics.precision_score(y_test, y_pred)*100
    recall_list[i] =  metrics.recall_score(y_test, y_pred)*100
    f1_list[i] = metrics.f1_score(y_test, y_pred)*100
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")
print(f"F1-Score:\n Mean = {f1_list.mean()}  Standard Deviation = {f1_list.std()}")

Model No.1
Confusion Matrix:
[[7330  909]
 [1136 1479]]
Accuracy = 81.15901971623364
Precision = 61.93467336683417
Recall = 56.558317399617586
F1-Score = 59.12452528482909


Model No.2
Confusion Matrix:
[[7283  936]
 [1146 1489]]
Accuracy = 80.81813156440022
Precision = 61.4020618556701
Recall = 56.50853889943074
F1-Score = 58.853754940711454


Model No.3
Confusion Matrix:
[[7346  881]
 [1136 1491]]
Accuracy = 81.41698912843192
Precision = 62.85834738617201
Recall = 56.75675675675676
F1-Score = 59.651930386077225


Model No.4
Confusion Matrix:
[[7303  946]
 [1135 1470]]
Accuracy = 80.82734475769303
Precision = 60.84437086092716
Recall = 56.4299424184261
F1-Score = 58.55407289384584


Model No.5
Confusion Matrix:
[[7380  878]
 [1146 1450]]
Accuracy = 81.35249677538235
Precision = 62.2852233676976
Recall = 55.855161787365184
F1-Score = 58.89520714865964


Model No.6
Confusion Matrix:
[[7385  846]
 [1180 1443]]
Accuracy = 81.33407038879675
Precision = 63.04062909567497
Recall = 55.0133434